apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: user-auth
  name: user-auth
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: user-auth
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: user-auth
    spec:
      containers:
      - env:
        - name: OAUTH_SIGN_KEY
          valueFrom:
            configMapKeyRef:
              key: OAUTH_SIGN_KEY
              name: card-matching-cluster-configmap
        image: cardmatching/user-auth:latest
        name: user-auth
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          httpGet:
            path: /health/live
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health/ready
            port: server
          initialDelaySeconds: 20
          periodSeconds: 3
        ports:
        - containerPort: 8080
          name: server
          protocol: TCP
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
